### ISSUE TITLE
Standardize all names and types

### ISSUE THREAD

**Issue by zhengqunkoo** [lekoook/h_comms#2]
Is it `dst` or `destAddr`? Is `destAddr` of type `uint8_t`? Is `lifetime` of type `uint64_t`?

**Comment by lekoook** [comment]
let's keep to `destAddr`, a little more specific.

the specs mentioned the destination address to be 32 bits, so that's why i used `uint32_t`. I guess we could just stick with the specs first then if we do want to minimize header size, we can reduce it later.
plus, the SocketTransceiver used socket ports as address. and i dont want to use port < 1024 since they are reserved. but if need to, we can apply simple mapping in SocketTransceiver for address [0,255]

i think `lifetime` should hold as large range as possible? since it could run for a long time.
